CREATE TABLE `users` (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`login` VARCHAR( 15 ) NOT NULL ,
`email` VARCHAR( 320 ) NOT NULL COMMENT '64(alias)+1(@)+255(domain)',
`pass` VARCHAR( 255 ) NOT NULL ,
`reset_code` VARCHAR( 255 ) NOT NULL ,
`total_followers` MEDIUMINT UNSIGNED NOT NULL ,
`total_followings` MEDIUMINT UNSIGNED NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE ( `login` ),
UNIQUE ( `email` )
);

CREATE TABLE `followers` (
`user_id` BIGINT UNSIGNED NOT NULL ,
`is_following_user_id` BIGINT UNSIGNED NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ( `user_id` , `is_following_user_id` )
);

CREATE TABLE `messages` (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`user_id` BIGINT UNSIGNED NOT NULL ,
`message` VARCHAR( 140 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `messages_user_references` (
`message_id` BIGINT UNSIGNED NOT NULL ,
`user_id` BIGINT UNSIGNED NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ( `message_id` , `user_id` )
);

CREATE TABLE `messages_topic_references` (
`message_id` BIGINT UNSIGNED NOT NULL ,
`topic_id` BIGINT UNSIGNED NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ( `message_id` , `topic_id` )
);

CREATE TABLE `topics` (
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`topic` VARCHAR( 136 ) NOT NULL ,
`mentions` MEDIUMINT UNSIGNED NOT NULL ,
`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE ( `topic` )
);